### ISSUE TITLE
Proposed Analyses for SP and TC scores

### ISSUE THREAD

**Issue by sjspielman** [spielmanlab/alignment_models#6]
First, compare all alignments to the _reference_ alignment, where the alignment w/ index is `50` is the *reference* alignment for all datasets.

+ For datasets with a single model, what is the mean/sd of scores?
     + R functions `mean()` and `sd()` can be used within `dplyr::summarize()`
     + We might want z-scores here
+ For datasets with 2 models
   + Where there are >=3 alignments identified per dataset (i.e. 40 are WAG and 10 are LG, but NOT 48 are WAG and 2 are LG), we want to do a series of t-tests (with corrections) to compare score distributions.
   + All around, we want strip plots (`geom_jitter()`)
+ For datasets with >= 3 models, for now just strip plots

**Comment by kittysocks** [comment]
This is 6/7 pull requests cannot be done in one!  June 22nd 2020
Notes below during meeting: 

1. For everything that has a single model compared to others, what is the score compared to those that have more than one model - want to make a table, and then make a couple representative plots (means of these 49 values) compare index[50] to everything else

2. alignment 50 is 1 and then there is other models in the rest of the mix 
.in the .csv files we have the 50 can be in either of the two columns  - can have 49 rows for each little grouping of scores

3. circumstance where there's two models found - do more stats - t - tests, need to have an instance where there's three alignments per dataset 

4. x axis is models and the y axis is the score for the alignment that gave you that model (jitter plot (((strip plots!)))) 

FIRST THINGS FIRST - make a table that you can make a histogram with (8 plots - TC/SP AA/NT DROS/EUP 


WRITE/READ - need to read before you write! 13 papers to read, build up reference citation for paper!!!
tan paper - if i filter badly made alignments i get a better tree, they think it's wrong! as a consequence the introduction gives a really good background of what softwares people use to filter, we're looking at different versions of an alignment, has to do with alignment uncertainty (we coooullld do - have all these alignments that give me a different model, what if i filter the alignment for blah, then i only get one model back) 

jordan and goldman paper 2012 read this too! 
spielman 2014 and 
potential di franco 2015
wong 2008 - little older but very short- says alignments give you problems! 
when reading paper - skip over the methods unless you're replicating the experiment! reading these papers to see the problems that alignments give you 
read introductions and then look at references in the introdution - if you see something you want to reference
1. author made it open access (never!)
2. get it from rowan
3. other aha (put DOI instead of name of paper)

**Comment by kittysocks** [comment]
Want to have two questions done by Monday. 
How many models per dataset? 
calculate top percent model -> look at readme, also change 01 script name to what it's specifically doing (same for headings)
We already have model percentage calculated, but it's not the top model percentage. Need to find the maximum percentage and then filter it
For example: mutate (max_x = max(x)) %>% mutate (filtered_item = filter(data_in_question == max_x) then go on
